// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ChatMessage struct {
	Uuid       pgtype.UUID
	ThreadUuid pgtype.UUID
	Role       string
	Content    string
	Emotion    pgtype.Text
	CreatedAt  pgtype.Timestamptz
}

type ChatThread struct {
	Uuid        pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	VisitorUuid pgtype.UUID
}

type Visitor struct {
	Uuid           pgtype.UUID
	IpAddress      string
	UserAgent      pgtype.Text
	AcceptLanguage pgtype.Text
	Referer        pgtype.Text
	Host           pgtype.Text
	ForwardedFor   pgtype.Text
	RawHeaders     pgtype.Text
	CreatedAt      pgtype.Timestamptz
	LastSeenAt     pgtype.Timestamptz
}
