// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: visitors.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVisitor = `-- name: CreateVisitor :one
INSERT INTO visitors (
  uuid,
  ip_address,
  user_agent,
  accept_language,
  referer,
  host,
  forwarded_for,
  raw_headers
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING uuid, ip_address, user_agent, accept_language, referer, host, forwarded_for, raw_headers, created_at, last_seen_at
`

type CreateVisitorParams struct {
	Uuid           pgtype.UUID
	IpAddress      string
	UserAgent      pgtype.Text
	AcceptLanguage pgtype.Text
	Referer        pgtype.Text
	Host           pgtype.Text
	ForwardedFor   pgtype.Text
	RawHeaders     pgtype.Text
}

func (q *Queries) CreateVisitor(ctx context.Context, arg CreateVisitorParams) (Visitor, error) {
	row := q.db.QueryRow(ctx, createVisitor,
		arg.Uuid,
		arg.IpAddress,
		arg.UserAgent,
		arg.AcceptLanguage,
		arg.Referer,
		arg.Host,
		arg.ForwardedFor,
		arg.RawHeaders,
	)
	var i Visitor
	err := row.Scan(
		&i.Uuid,
		&i.IpAddress,
		&i.UserAgent,
		&i.AcceptLanguage,
		&i.Referer,
		&i.Host,
		&i.ForwardedFor,
		&i.RawHeaders,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getVisitor = `-- name: GetVisitor :one
SELECT uuid, ip_address, user_agent, accept_language, referer, host, forwarded_for, raw_headers, created_at, last_seen_at FROM visitors
WHERE uuid = $1
`

func (q *Queries) GetVisitor(ctx context.Context, uuid pgtype.UUID) (Visitor, error) {
	row := q.db.QueryRow(ctx, getVisitor, uuid)
	var i Visitor
	err := row.Scan(
		&i.Uuid,
		&i.IpAddress,
		&i.UserAgent,
		&i.AcceptLanguage,
		&i.Referer,
		&i.Host,
		&i.ForwardedFor,
		&i.RawHeaders,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const updateVisitorLastSeen = `-- name: UpdateVisitorLastSeen :one
UPDATE visitors
SET
  last_seen_at = now(),
  ip_address = $2,
  user_agent = $3,
  accept_language = $4,
  referer = $5,
  host = $6,
  forwarded_for = $7,
  raw_headers = $8
WHERE uuid = $1
RETURNING uuid, ip_address, user_agent, accept_language, referer, host, forwarded_for, raw_headers, created_at, last_seen_at
`

type UpdateVisitorLastSeenParams struct {
	Uuid           pgtype.UUID
	IpAddress      string
	UserAgent      pgtype.Text
	AcceptLanguage pgtype.Text
	Referer        pgtype.Text
	Host           pgtype.Text
	ForwardedFor   pgtype.Text
	RawHeaders     pgtype.Text
}

func (q *Queries) UpdateVisitorLastSeen(ctx context.Context, arg UpdateVisitorLastSeenParams) (Visitor, error) {
	row := q.db.QueryRow(ctx, updateVisitorLastSeen,
		arg.Uuid,
		arg.IpAddress,
		arg.UserAgent,
		arg.AcceptLanguage,
		arg.Referer,
		arg.Host,
		arg.ForwardedFor,
		arg.RawHeaders,
	)
	var i Visitor
	err := row.Scan(
		&i.Uuid,
		&i.IpAddress,
		&i.UserAgent,
		&i.AcceptLanguage,
		&i.Referer,
		&i.Host,
		&i.ForwardedFor,
		&i.RawHeaders,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}
